# Generated by Django 3.0.6 on 2020-06-10 09:06

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtatSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divers', models.CharField(max_length=255)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('autres', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Direction')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='etat_site',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.EtatSite'),
        ),
        migrations.AddField(
            model_name='direction',
            name='hebergement',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.Hebergement'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('autres', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Direction')),
            ],
        ),
    ]
