# Generated by Django 3.0.6 on 2020-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0002_auto_20200610_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='url_site',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='version_joomla',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
