# Generated by Django 3.0.6 on 2020-06-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0002_auto_20200603_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='etat_site',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divers', models.TextField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=255, null=True)),
                ('prenom', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.CharField(default=None, max_length=255, null=True)),
                ('telephone', models.CharField(default=None, max_length=255, null=True)),
                ('autres', models.TextField(default=None, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=255, null=True)),
                ('hebergeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Hebergeur')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=255, null=True)),
                ('prenom', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.CharField(default=None, max_length=255, null=True)),
                ('telephone', models.CharField(default=None, max_length=255, null=True)),
                ('autres', models.TextField(default=None, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Direction')),
            ],
        ),
    ]
