# Generated by Django 3.0.6 on 2020-06-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_auto_20200610_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('commentaires', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Direction')),
            ],
        ),
    ]
