# Generated by Django 3.0.6 on 2020-06-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_auto_20200603_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='etat_site',
        ),
    ]
