# Generated by Django 3.0.6 on 2020-06-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0005_direction_etat_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergement',
            name='hebergeur',
        ),
        migrations.AddField(
            model_name='hebergeur',
            name='hebergement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.Hebergement'),
        ),
    ]
