# Generated by Django 3.0.6 on 2020-06-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0007_remove_hebergeur_hebergement'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='hebergement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.Hebergement'),
        ),
    ]
