# Generated by Django 3.0.6 on 2020-06-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0009_auto_20200604_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='hebergement',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.Hebergement'),
        ),
    ]
