version: '3'
services:
  web:
    build: .
    environment:
      GESTION_DDSSP_ENV: docker
    ports:
      - "6080:6080"
    networks:
      - database_bdd

networks:
  database_bdd:
    external: true