version: "2"
services:
    db:
        image: mysql
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - bdd

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 80:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        networks:
            - bdd
volumes:
    persistent:

networks:
    bdd:
        driver: bridge
