# Generated by Django 3.0.6 on 2020-06-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carte', '0004_remove_direction_etat_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Direction')),
            ],
        ),
    ]
